version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: regress
    volumes:
      - db_data:/var/lib/postgresql/data
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
  pdf-ingest:
    build:
      context: .
      dockerfile: services/pdf-ingest/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
      MESSAGE_BROKER_URL: kafka:9092
    ports:
      - "8081:8081"
  text-extraction:
    build:
      context: .
      dockerfile: services/text-extraction/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
      MESSAGE_BROKER_URL: kafka:9092
    ports:
      - "8083:8083"
  prompt-manager:
    build:
      context: .
      dockerfile: services/prompt-manager/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
    ports:
      - "8082:8082"
  classifier:
    build:
      context: .
      dockerfile: services/classifier/Dockerfile
    environment:
      OPENAI_API_KEY: "sk-proj-tUvEXQuoFPPstEtXdpQN7E2TETKlsLSzjqXn-9pKto3wUlON2lYCTRNV_XZEx0D8UzstlNS8hPT3BlbkFJAxFPCiMLCUziTETVR0GPHiDQXp9li7FG37nmrdMi9T7-3bF5E8t19e8Jj-yk_TsFC-rWSD15oAs"
    ports:
      - "8084:8084"
  metrics:
    build:
      context: .
      dockerfile: services/metrics/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
    ports:
      - "8085:8085"
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=11111111111111111111
    ports:
      - "9092:9092"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:80"

volumes:
  db_data:
