version: '3.9'
services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
  pdf-ingest:
    build: ./services/pdf-ingest
    ports:
      - "8081:8081"
  text-extraction:
    build: ./services/text-extraction
  prompt-manager:
    build: ./services/prompt-manager
    ports:
      - "8082:8082"
  classifier:
    build: ./services/classifier
