version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: regress
    volumes:
      - db_data:/var/lib/postgresql/data
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
  pdf-ingest:
    build:
      context: .
      dockerfile: services/pdf-ingest/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
      MESSAGE_BROKER_URL: kafka:9092
    ports:
      - "8081:8081"
  text-extraction:
    build:
      context: .
      dockerfile: services/text-extraction/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
      MESSAGE_BROKER_URL: kafka:9092
    ports:
      - "8083:8083"
  prompt-manager:
    build:
      context: .
      dockerfile: services/prompt-manager/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/regress
    ports:
      - "8082:8082"
  classifier:
    build:
      context: .
      dockerfile: services/classifier/Dockerfile
    ports:
      - "8084:8084"
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

volumes:
  db_data:
