-- Add OCR/Layout metadata columns to pdf_texts.
ALTER TABLE pdf_texts ADD COLUMN IF NOT EXISTS ocr_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pdf_texts ADD COLUMN IF NOT EXISTS char_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pdf_texts ADD COLUMN IF NOT EXISTS lang TEXT;
ALTER TABLE pdf_texts ADD COLUMN IF NOT EXISTS has_bbox BOOLEAN;
ALTER TABLE pdf_texts ADD COLUMN IF NOT EXISTS layout_json JSONB;
