[package]
name = "classifier"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
async-trait.workspace = true
shared = { path = "../../shared" }
