[package]
name = "pdf-ingest"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
shared = { path = "../../shared" }
