[build]
jobs = 1

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C","link-arg=-fuse-ld=lld","-C","codegen-units=1","-C","debuginfo=0"]

[profile.release]
opt-level = 1
codegen-units = 1
debug = 0
lto = "off"
panic = "unwind"
incremental = false
